//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.13 at 06:17:06 PM CEST 
//


package demo_gen;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo_gen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo_gen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCalculationRequest }
     * 
     */
    public GetCalculationRequest createGetCalculationRequest() {
        return new GetCalculationRequest();
    }

    /**
     * Create an instance of {@link GetCalculationResponse }
     * 
     */
    public GetCalculationResponse createGetCalculationResponse() {
        return new GetCalculationResponse();
    }

    /**
     * Create an instance of {@link CalculationResult }
     * 
     */
    public CalculationResult createCalculationResult() {
        return new CalculationResult();
    }

}
