//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.13 at 06:17:06 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "demo-gen", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package demo_gen;
